# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c61f6e7b604e60b5b4dddff10dcc0c4437300746b4ab828ba39f42ce84b3671c2b990aad839388970b6e56927a60a8a0acb9b8a4e90bb517bc1cb2a9678ff25e

test:
  secret_key_base: adf462ea92817c2cfa322b7f9efbfc1eac3b3cba1bcc6b94fc8230e71b9fdb3b002e6115ae8c4f93dcb6a45d7966866e93f962f11711dfe28b341bf71b1259bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
